version: '3'

services:

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
      POSTGRES_DB: bank
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/configuration/postgresql:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080

  bank-java-spring:
    image: valaszek/bank:latest
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - database